services:
  redis:
    image: redis:latest
    container_name: perceptryx_redis
    ports:
      - "6382:6379"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: perceptryx_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped